# Generated by Django 6.0.4 on 2026-04-21 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_movie_keywords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='keywords',
        ),
    ]
